export const testSummonerData : any = {"id":67972542,"accountId":228054520,"name":"ShuntStick","profileIconId":982,"revisionDate":1515464902000,"summonerLevel":46};
export const testMatchInformation: any = {
    "seasonId": 13,
    "queueId": 450,
    "gameId": 3148607657,
    "participantIdentities": [
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "ZenithLost",
                "matchHistoryUri": "/v1/stats/player_history/NA1/46218558",
                "platformId": "NA1",
                "currentAccountId": "6gY6GWAWyvs-fTE-4k20Y2Uib8giZTbpSHSTNn-F6wbB_A",
                "profileIcon": 4281,
                "summonerId": "Ks8vU4d9EYR4TRyNUfCUtJvw99KJmCDmcVblFGQLUWboaxY",
                "accountId": "6gY6GWAWyvs-fTE-4k20Y2Uib8giZTbpSHSTNn-F6wbB_A"
            },
            "participantId": 1
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "saynotopi",
                "matchHistoryUri": "/v1/stats/player_history/NA1/220261832",
                "platformId": "NA1",
                "currentAccountId": "EBpK53rSGVRdn46jPA0bMveob5HMj2cJnrBQkRw7gJFSa-c",
                "profileIcon": 3860,
                "summonerId": "D9emARdA6qtKCShPDIZgWJutKl-KmlEtF0qGpw6O9d2I42c",
                "accountId": "EBpK53rSGVRdn46jPA0bMveob5HMj2cJnrBQkRw7gJFSa-c"
            },
            "participantId": 2
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "MannyQuinn",
                "matchHistoryUri": "/v1/stats/player_history/NA1/44890557",
                "platformId": "NA1",
                "currentAccountId": "6o49MDBfNYHzEGQx1v9jmBZNuXhhRoh7zLkjRmXVtTNetQ",
                "profileIcon": 4070,
                "summonerId": "CbRxqnlz9M-R4VqexNNhgTsUajPWS-_p4ZaGQbvDvSStC7g",
                "accountId": "6o49MDBfNYHzEGQx1v9jmBZNuXhhRoh7zLkjRmXVtTNetQ"
            },
            "participantId": 3
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "KsLPraise",
                "matchHistoryUri": "/v1/stats/player_history/NA1/201312706",
                "platformId": "NA1",
                "currentAccountId": "uBDi0iSyeH4O5csMsPyCynXx-Ag_jMiOeAVvjN3RXOTQmaE",
                "profileIcon": 4231,
                "summonerId": "Th-scbBenL6kgOk6zG4uW5yRtXeFD6am5lMpsdXABUw-VFY",
                "accountId": "uBDi0iSyeH4O5csMsPyCynXx-Ag_jMiOeAVvjN3RXOTQmaE"
            },
            "participantId": 4
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "ShuntStick",
                "matchHistoryUri": "/v1/stats/player_history/NA1/228054520",
                "platformId": "NA1",
                "currentAccountId": "y51KncyyCqO2JDGsbLaVCFwAbcajI3WebeSpdPHzyAhBjRQ",
                "profileIcon": 3381,
                "summonerId": "ePijM0fYL6JMwUeN9EAnlBRNcDBRsWA8yqCScsWjC3hw7eU",
                "accountId": "y51KncyyCqO2JDGsbLaVCFwAbcajI3WebeSpdPHzyAhBjRQ"
            },
            "participantId": 5
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "UncleCan",
                "matchHistoryUri": "/v1/stats/player_history/NA1/213451366",
                "platformId": "NA1",
                "currentAccountId": "Uj2K5HgyFN0fL1bNJRAVzQZuv-Yoh5EADGDaNRfcNSAmGK4",
                "profileIcon": 4199,
                "summonerId": "fjoUh10HtQjTIuMCLjaIXV9njq-YNOmvApv86uCV9_QpLug",
                "accountId": "Uj2K5HgyFN0fL1bNJRAVzQZuv-Yoh5EADGDaNRfcNSAmGK4"
            },
            "participantId": 6
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "GeiDian QianQian",
                "matchHistoryUri": "/v1/stats/player_history/NA1/228621665",
                "platformId": "NA1",
                "currentAccountId": "aFpyaCCnc06YHhJ3GYA8E9RkQ_hIq9LmpEzKCnEcKWOegiE",
                "profileIcon": 3799,
                "summonerId": "S3bWYOloi8vROM4_scmDCRII0XgKAJHR08Rgb-mFK_ImT3A",
                "accountId": "aFpyaCCnc06YHhJ3GYA8E9RkQ_hIq9LmpEzKCnEcKWOegiE"
            },
            "participantId": 7
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Lv6 Annie",
                "matchHistoryUri": "/v1/stats/player_history/NA1/230864502",
                "platformId": "NA1",
                "currentAccountId": "cM1SNgSM-UdrZWTN8fJ4qoZQPDphwNXNdd6UxTmSx7Hi-KY",
                "profileIcon": 1433,
                "summonerId": "OiRViGPkB92EBZUHY6ifxl94QvUtfsH4zJkz062i7B6I5UM",
                "accountId": "cM1SNgSM-UdrZWTN8fJ4qoZQPDphwNXNdd6UxTmSx7Hi-KY"
            },
            "participantId": 8
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "GeiDian LianLian",
                "matchHistoryUri": "/v1/stats/player_history/NA1/209609730",
                "platformId": "NA1",
                "currentAccountId": "ufW0v0EcklJUTzNu8jEsI30fKdzuUSX_aG7vJP1vwpJzHjA",
                "profileIcon": 4200,
                "summonerId": "9sN78I-4fSemwUk33FtRIa9iu1-FK2iYo2S3gKJx9sksgTY",
                "accountId": "ufW0v0EcklJUTzNu8jEsI30fKdzuUSX_aG7vJP1vwpJzHjA"
            },
            "participantId": 9
        },
        {
            "player": {
                "currentPlatformId": "NA1",
                "summonerName": "Rqwest",
                "matchHistoryUri": "/v1/stats/player_history/NA1/46346899",
                "platformId": "NA1",
                "currentAccountId": "DJEL02420yAkONz975ccSmP84VSIDXh8D-XNLw-zwZDYHA",
                "profileIcon": 4027,
                "summonerId": "lQPUallQMQ1I7O6n-_H93gYI22NgfLOG6aZyR1fG2KRDJf0",
                "accountId": "DJEL02420yAkONz975ccSmP84VSIDXh8D-XNLw-zwZDYHA"
            },
            "participantId": 10
        }
    ],
    "gameVersion": "9.18.288.7871",
    "platformId": "NA1",
    "gameMode": "ARAM",
    "mapId": 12,
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "firstDragon": false,
            "bans": [],
            "firstInhibitor": true,
            "win": "Win",
            "firstRiftHerald": false,
            "firstBaron": false,
            "baronKills": 0,
            "riftHeraldKills": 0,
            "firstBlood": true,
            "teamId": 100,
            "firstTower": true,
            "vilemawKills": 0,
            "inhibitorKills": 1,
            "towerKills": 4,
            "dominionVictoryScore": 0,
            "dragonKills": 0
        },
        {
            "firstDragon": false,
            "bans": [],
            "firstInhibitor": false,
            "win": "Fail",
            "firstRiftHerald": false,
            "firstBaron": false,
            "baronKills": 0,
            "riftHeraldKills": 0,
            "firstBlood": false,
            "teamId": 200,
            "firstTower": false,
            "vilemawKills": 0,
            "inhibitorKills": 0,
            "towerKills": 0,
            "dominionVictoryScore": 0,
            "dragonKills": 0
        }
    ],
    "participants": [
        {
            "spell1Id": 14,
            "participantId": 1,
            "timeline": {
                "lane": "NONE",
                "participantId": 1,
                "csDiffPerMinDeltas": {
                    "0-10": 0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 512.4
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 2.8
                },
                "xpPerMinDeltas": {
                    "0-10": 657.2
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 873.3000000000001
                }
            },
            "spell2Id": 4,
            "teamId": 100,
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 943,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 32,
                "longestTimeSpentLiving": 280,
                "perk1Var1": 868,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8014,
                "perk4": 9111,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 4,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 322,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 3318,
                "physicalDamageDealtToChampions": 9273,
                "damageDealtToObjectives": 3318,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 18,
                "perk4Var1": 526,
                "totalDamageTaken": 12241,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "quadraKills": 0,
                "magicDamageDealt": 2549,
                "item2": 0,
                "item3": 3043,
                "item0": 3812,
                "item1": 1001,
                "item6": 2052,
                "item4": 0,
                "item5": 0,
                "perk1": 8139,
                "perk0": 8128,
                "perk3": 8135,
                "perk2": 8138,
                "perk3Var3": 0,
                "perk3Var2": 5,
                "perk3Var1": 789,
                "damageSelfMitigated": 7625,
                "magicalDamageTaken": 6295,
                "perk0Var2": 14,
                "firstInhibitorKill": false,
                "trueDamageTaken": 1140,
                "assists": 20,
                "perk4Var2": 240,
                "goldSpent": 6450,
                "trueDamageDealt": 252,
                "participantId": 1,
                "physicalDamageDealt": 34805,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 10469,
                "physicalDamageTaken": 4805,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 37606,
                "deaths": 4,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "turretKills": 2,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 252,
                "goldEarned": 8939,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": true,
                "champLevel": 13,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 689,
                "combatPlayerScore": 0,
                "perk0Var3": 834,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 3269,
                "totalMinionsKilled": 42,
                "timeCCingOthers": 3,
                "statPerk2": 5001
            },
            "championId": 126
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 5405,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 161,
                "longestTimeSpentLiving": 392,
                "perk1Var1": 0,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8139,
                "perk4": 8134,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 2,
                "playerScore1": 3,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 436,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 875,
                "physicalDamageDealtToChampions": 181,
                "damageDealtToObjectives": 875,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 5,
                "perk2Var1": 3,
                "perk4Var1": 17,
                "totalDamageTaken": 6443,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 11802,
                "item2": 3108,
                "item3": 2423,
                "item0": 3030,
                "item1": 2031,
                "item6": 0,
                "item4": 3111,
                "item5": 0,
                "perk1": 8313,
                "perk0": 8351,
                "perk3": 8347,
                "perk2": 8345,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 0,
                "damageSelfMitigated": 3904,
                "magicalDamageTaken": 5169,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 82,
                "assists": 25,
                "perk4Var2": 5,
                "goldSpent": 5050,
                "trueDamageDealt": 564,
                "participantId": 2,
                "physicalDamageDealt": 4076,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 6151,
                "physicalDamageTaken": 1191,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 16442,
                "deaths": 2,
                "perkPrimaryStyle": 8300,
                "perkSubStyle": 8100,
                "turretKills": 1,
                "firstBloodKill": true,
                "trueDamageDealtToChampions": 564,
                "goldEarned": 8078,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": true,
                "firstTowerKill": false,
                "champLevel": 14,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 3,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 5997,
                "totalMinionsKilled": 12,
                "timeCCingOthers": 19,
                "statPerk2": 5003
            },
            "spell1Id": 14,
            "participantId": 2,
            "highestAchievedSeasonTier": "SILVER",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "NONE",
                "participantId": 2,
                "csDiffPerMinDeltas": {
                    "0-10": 0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 467.9
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 1
                },
                "xpPerMinDeltas": {
                    "0-10": 784.9
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 468.7
                }
            },
            "championId": 267
        },
        {
            "spell1Id": 7,
            "participantId": 3,
            "timeline": {
                "lane": "NONE",
                "participantId": 3,
                "csDiffPerMinDeltas": {
                    "0-10": 0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 751.8
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 4.5
                },
                "xpPerMinDeltas": {
                    "0-10": 740.4
                },
                "role": "DUO",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 671.6
                }
            },
            "spell2Id": 4,
            "teamId": 100,
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 1243,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 35,
                "longestTimeSpentLiving": 281,
                "perk1Var1": 440,
                "perk1Var3": 0,
                "perk1Var2": 220,
                "tripleKills": 0,
                "perk5": 8135,
                "perk4": 8139,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 12,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 2,
                "playerScore6": 0,
                "perk5Var1": 740,
                "perk5Var3": 0,
                "perk5Var2": 5,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 3073,
                "physicalDamageDealtToChampions": 12766,
                "damageDealtToObjectives": 3073,
                "perk2Var2": 50,
                "perk2Var3": 0,
                "totalUnitsHealed": 4,
                "perk2Var1": 4,
                "perk4Var1": 733,
                "totalDamageTaken": 8973,
                "perk4Var3": 0,
                "largestCriticalStrike": 716,
                "largestKillingSpree": 5,
                "quadraKills": 0,
                "magicDamageDealt": 2276,
                "item2": 3094,
                "item3": 0,
                "item0": 3031,
                "item1": 1001,
                "item6": 2052,
                "item4": 0,
                "item5": 0,
                "perk1": 9111,
                "perk0": 8005,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 460,
                "damageSelfMitigated": 4098,
                "magicalDamageTaken": 4526,
                "perk0Var2": 474,
                "firstInhibitorKill": false,
                "trueDamageTaken": 461,
                "assists": 10,
                "perk4Var2": 0,
                "goldSpent": 6400,
                "trueDamageDealt": 0,
                "participantId": 3,
                "physicalDamageDealt": 60698,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 14009,
                "physicalDamageTaken": 3986,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 62975,
                "deaths": 3,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "turretKills": 1,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 10988,
                "killingSprees": 3,
                "unrealKills": 0,
                "firstTowerAssist": true,
                "firstTowerKill": false,
                "champLevel": 14,
                "doubleKills": 3,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 594,
                "combatPlayerScore": 0,
                "perk0Var3": 119,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 3821,
                "totalMinionsKilled": 65,
                "timeCCingOthers": 18,
                "statPerk2": 5002
            },
            "championId": 51
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 4791,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 11,
                "longestTimeSpentLiving": 296,
                "perk1Var1": 250,
                "perk1Var3": 0,
                "perk1Var2": 278,
                "tripleKills": 0,
                "perk5": 8014,
                "perk4": 8009,
                "playerScore9": 0,
                "playerScore8": 3,
                "kills": 2,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 129,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5007,
                "damageDealtToTurrets": 219,
                "physicalDamageDealtToChampions": 960,
                "damageDealtToObjectives": 219,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 5,
                "perk2Var1": 14,
                "perk4Var1": 3103,
                "totalDamageTaken": 10064,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "quadraKills": 0,
                "magicDamageDealt": 7448,
                "item2": 3100,
                "item3": 3802,
                "item0": 3073,
                "item1": 3158,
                "item6": 2052,
                "item4": 0,
                "item5": 0,
                "perk1": 8226,
                "perk0": 8214,
                "perk3": 8237,
                "perk2": 8210,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 288,
                "damageSelfMitigated": 4754,
                "magicalDamageTaken": 4480,
                "perk0Var2": 853,
                "firstInhibitorKill": true,
                "trueDamageTaken": 755,
                "assists": 28,
                "perk4Var2": 128,
                "goldSpent": 6500,
                "trueDamageDealt": 0,
                "participantId": 4,
                "physicalDamageDealt": 1726,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 5752,
                "physicalDamageTaken": 4828,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 9174,
                "deaths": 5,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8000,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 7793,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 13,
                "doubleKills": 0,
                "inhibitorKills": 1,
                "firstInhibitorAssist": false,
                "perk0Var1": 236,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 4562,
                "totalMinionsKilled": 2,
                "timeCCingOthers": 4,
                "statPerk2": 5003
            },
            "spell1Id": 4,
            "participantId": 4,
            "highestAchievedSeasonTier": "SILVER",
            "spell2Id": 13,
            "teamId": 100,
            "timeline": {
                "lane": "NONE",
                "participantId": 4,
                "csDiffPerMinDeltas": {
                    "0-10": 0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 453.7
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.1
                },
                "xpPerMinDeltas": {
                    "0-10": 692.2
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 638.4
                }
            },
            "championId": 37
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 16776,
                "largestMultiKill": 3,
                "totalTimeCrowdControlDealt": 63,
                "longestTimeSpentLiving": 361,
                "perk1Var1": 350,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 1,
                "perk5": 8014,
                "perk4": 8009,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 11,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 590,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 834,
                "physicalDamageDealtToChampions": 182,
                "damageDealtToObjectives": 834,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 30,
                "perk4Var1": 2713,
                "totalDamageTaken": 9879,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 3,
                "quadraKills": 0,
                "magicDamageDealt": 36452,
                "item2": 1052,
                "item3": 0,
                "item0": 3285,
                "item1": 3165,
                "item6": 2052,
                "item4": 0,
                "item5": 3020,
                "perk1": 8126,
                "perk0": 8128,
                "perk3": 8106,
                "perk2": 8138,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 5,
                "damageSelfMitigated": 4442,
                "magicalDamageTaken": 4057,
                "perk0Var2": 20,
                "firstInhibitorKill": false,
                "trueDamageTaken": 717,
                "assists": 17,
                "perk4Var2": 71,
                "goldSpent": 7735,
                "trueDamageDealt": 284,
                "participantId": 5,
                "physicalDamageDealt": 2721,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 17243,
                "physicalDamageTaken": 5104,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 39458,
                "deaths": 4,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 284,
                "goldEarned": 9262,
                "killingSprees": 3,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 13,
                "doubleKills": 2,
                "inhibitorKills": 0,
                "firstInhibitorAssist": true,
                "perk0Var1": 1330,
                "combatPlayerScore": 0,
                "perk0Var3": 1322,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 256,
                "totalMinionsKilled": 30,
                "timeCCingOthers": 14,
                "statPerk2": 5002
            },
            "spell1Id": 13,
            "participantId": 5,
            "highestAchievedSeasonTier": "SILVER",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "NONE",
                "participantId": 5,
                "csDiffPerMinDeltas": {
                    "0-10": 0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 515.5
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.9
                },
                "xpPerMinDeltas": {
                    "0-10": 737.2
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 617.8
                }
            },
            "championId": 101
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 37,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 89,
                "longestTimeSpentLiving": 116,
                "perk1Var1": 334,
                "perk1Var3": 0,
                "perk1Var2": 120,
                "tripleKills": 0,
                "perk5": 8106,
                "perk4": 8139,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 3,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 5,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5005,
                "damageDealtToTurrets": 428,
                "physicalDamageDealtToChampions": 9282,
                "damageDealtToObjectives": 428,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 0,
                "perk4Var1": 810,
                "totalDamageTaken": 13889,
                "perk4Var3": 0,
                "largestCriticalStrike": 372,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 82,
                "item2": 2031,
                "item3": 3086,
                "item0": 3031,
                "item1": 3006,
                "item6": 2052,
                "item4": 2015,
                "item5": 0,
                "perk1": 9111,
                "perk0": 8008,
                "perk3": 8014,
                "perk2": 9103,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 260,
                "damageSelfMitigated": 6510,
                "magicalDamageTaken": 7411,
                "perk0Var2": 10,
                "firstInhibitorKill": false,
                "trueDamageTaken": 238,
                "assists": 9,
                "perk4Var2": 0,
                "goldSpent": 6550,
                "trueDamageDealt": 1233,
                "participantId": 6,
                "physicalDamageDealt": 16060,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 10252,
                "physicalDamageTaken": 6240,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 17377,
                "deaths": 9,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 932,
                "goldEarned": 7290,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 11,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 1,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 1580,
                "totalMinionsKilled": 19,
                "timeCCingOthers": 11,
                "statPerk2": 5001
            },
            "spell1Id": 21,
            "participantId": 6,
            "highestAchievedSeasonTier": "GOLD",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "NONE",
                "participantId": 6,
                "csDiffPerMinDeltas": {
                    "0-10": -0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 462
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.7
                },
                "xpPerMinDeltas": {
                    "0-10": 578.3
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 1002.2
                }
            },
            "championId": 29
        },
        {
            "spell1Id": 4,
            "participantId": 7,
            "timeline": {
                "lane": "NONE",
                "participantId": 7,
                "csDiffPerMinDeltas": {
                    "0-10": -0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 401.2
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.3
                },
                "xpPerMinDeltas": {
                    "0-10": 651.9
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 775.5
                }
            },
            "spell2Id": 32,
            "teamId": 200,
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 3483,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 89,
                "longestTimeSpentLiving": 305,
                "perk1Var1": 306,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8210,
                "perk4": 8226,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 1,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 5,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 0,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5002,
                "statPerk0": 5005,
                "damageDealtToTurrets": 57,
                "physicalDamageDealtToChampions": 654,
                "damageDealtToObjectives": 57,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 4,
                "perk2Var1": 209,
                "perk4Var1": 200,
                "totalDamageTaken": 13019,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 22114,
                "item2": 1058,
                "item3": 1058,
                "item0": 2031,
                "item1": 3152,
                "item6": 2052,
                "item4": 0,
                "item5": 0,
                "perk1": 8463,
                "perk0": 8439,
                "perk3": 8451,
                "perk2": 8473,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 161,
                "damageSelfMitigated": 6816,
                "magicalDamageTaken": 6654,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 579,
                "assists": 7,
                "perk4Var2": 0,
                "goldSpent": 5150,
                "trueDamageDealt": 415,
                "participantId": 7,
                "physicalDamageDealt": 2386,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 4453,
                "physicalDamageTaken": 5786,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 24915,
                "deaths": 5,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8200,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 315,
                "goldEarned": 6761,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 12,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 0,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 2531,
                "totalMinionsKilled": 19,
                "timeCCingOthers": 10,
                "statPerk2": 5001
            },
            "championId": 127
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 7290,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 48,
                "longestTimeSpentLiving": 581,
                "perk1Var1": 250,
                "perk1Var3": 0,
                "perk1Var2": 238,
                "tripleKills": 0,
                "perk5": 8105,
                "perk4": 8126,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 6,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 16,
                "perk5Var3": 0,
                "perk5Var2": 5,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 187,
                "physicalDamageDealtToChampions": 205,
                "damageDealtToObjectives": 187,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 5,
                "perk2Var1": 0,
                "perk4Var1": 175,
                "totalDamageTaken": 4747,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 6,
                "quadraKills": 0,
                "magicDamageDealt": 9724,
                "item2": 0,
                "item3": 1052,
                "item0": 3285,
                "item1": 3089,
                "item6": 2052,
                "item4": 0,
                "item5": 0,
                "perk1": 8226,
                "perk0": 8229,
                "perk3": 8237,
                "perk2": 8210,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 315,
                "damageSelfMitigated": 1742,
                "magicalDamageTaken": 3077,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 65,
                "assists": 11,
                "perk4Var2": 0,
                "goldSpent": 7235,
                "trueDamageDealt": 385,
                "participantId": 8,
                "physicalDamageDealt": 889,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 7881,
                "physicalDamageTaken": 1604,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 10999,
                "deaths": 2,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 385,
                "goldEarned": 7751,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 13,
                "doubleKills": 1,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 1137,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 2456,
                "totalMinionsKilled": 8,
                "timeCCingOthers": 21,
                "statPerk2": 5001
            },
            "spell1Id": 13,
            "participantId": 8,
            "highestAchievedSeasonTier": "GOLD",
            "spell2Id": 3,
            "teamId": 200,
            "timeline": {
                "lane": "NONE",
                "participantId": 8,
                "csDiffPerMinDeltas": {
                    "0-10": -0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 504.8
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.7
                },
                "xpPerMinDeltas": {
                    "0-10": 748.5
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 280.1
                }
            },
            "championId": 350
        },
        {
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 1049,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 20,
                "longestTimeSpentLiving": 183,
                "perk1Var1": 269,
                "perk1Var3": 0,
                "perk1Var2": 120,
                "tripleKills": 0,
                "perk5": 8234,
                "perk4": 8275,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 6,
                "playerScore1": 1,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 5105,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5005,
                "damageDealtToTurrets": 0,
                "physicalDamageDealtToChampions": 3282,
                "damageDealtToObjectives": 0,
                "perk2Var2": 30,
                "perk2Var3": 0,
                "totalUnitsHealed": 3,
                "perk2Var1": 8,
                "perk4Var1": 5,
                "totalDamageTaken": 11988,
                "perk4Var3": 0,
                "largestCriticalStrike": 425,
                "largestKillingSpree": 2,
                "quadraKills": 0,
                "magicDamageDealt": 7412,
                "item2": 3006,
                "item3": 0,
                "item0": 3087,
                "item1": 3031,
                "item6": 0,
                "item4": 0,
                "item5": 0,
                "perk1": 9111,
                "perk0": 8021,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 160,
                "damageSelfMitigated": 4550,
                "magicalDamageTaken": 5481,
                "perk0Var2": 0,
                "firstInhibitorKill": false,
                "trueDamageTaken": 190,
                "assists": 6,
                "perk4Var2": 0,
                "goldSpent": 7250,
                "trueDamageDealt": 1986,
                "participantId": 9,
                "physicalDamageDealt": 14011,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 4908,
                "physicalDamageTaken": 6316,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 23410,
                "deaths": 7,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 576,
                "goldEarned": 8104,
                "killingSprees": 2,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 12,
                "doubleKills": 2,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 413,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 1788,
                "totalMinionsKilled": 32,
                "timeCCingOthers": 3,
                "statPerk2": 5001
            },
            "spell1Id": 4,
            "participantId": 9,
            "highestAchievedSeasonTier": "GOLD",
            "spell2Id": 7,
            "teamId": 200,
            "timeline": {
                "lane": "NONE",
                "participantId": 9,
                "csDiffPerMinDeltas": {
                    "0-10": -0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 516.4
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 2.2
                },
                "xpPerMinDeltas": {
                    "0-10": 700.6
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 801.8
                }
            },
            "championId": 67
        },
        {
            "spell1Id": 32,
            "participantId": 10,
            "timeline": {
                "lane": "NONE",
                "participantId": 10,
                "csDiffPerMinDeltas": {
                    "0-10": -0.54
                },
                "goldPerMinDeltas": {
                    "0-10": 475.20000000000005
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -52.75999999999999
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.7000000000000002
                },
                "xpPerMinDeltas": {
                    "0-10": 668.8
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 75.27999999999989
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 786.6
                }
            },
            "spell2Id": 4,
            "teamId": 200,
            "stats": {
                "firstBloodAssist": false,
                "visionScore": 0,
                "magicDamageDealtToChampions": 12668,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 12,
                "longestTimeSpentLiving": 109,
                "perk1Var1": 250,
                "perk1Var3": 0,
                "perk1Var2": 160,
                "tripleKills": 0,
                "perk5": 8236,
                "perk4": 8233,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 2,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 3,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 24,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5005,
                "damageDealtToTurrets": 0,
                "physicalDamageDealtToChampions": 833,
                "damageDealtToObjectives": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 8,
                "perk4Var1": 6,
                "totalDamageTaken": 11795,
                "perk4Var3": 0,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 44480,
                "item2": 1058,
                "item3": 1001,
                "item0": 3057,
                "item1": 3285,
                "item6": 2052,
                "item4": 1058,
                "item5": 0,
                "perk1": 9111,
                "perk0": 8005,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 136,
                "damageSelfMitigated": 3933,
                "magicalDamageTaken": 6536,
                "perk0Var2": 96,
                "firstInhibitorKill": false,
                "trueDamageTaken": 27,
                "assists": 14,
                "perk4Var2": 0,
                "goldSpent": 7050,
                "trueDamageDealt": 990,
                "participantId": 10,
                "physicalDamageDealt": 1630,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 14427,
                "physicalDamageTaken": 5232,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 47102,
                "deaths": 8,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 925,
                "goldEarned": 8189,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 13,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "firstInhibitorAssist": false,
                "perk0Var1": 96,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 0,
                "pentaKills": 0,
                "totalHeal": 453,
                "totalMinionsKilled": 31,
                "timeCCingOthers": 10,
                "statPerk2": 5001
            },
            "championId": 4
        }
    ],
    "gameDuration": 794,
    "gameCreation": 1568350272591
};
export const testRecentMatchData : any = {
    "matches": [
        {
            "lane": "NONE",
            "gameId": 3148607657,
            "champion": 101,
            "platformId": "NA1",
            "timestamp": 1568350272591,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148601956,
            "champion": 412,
            "platformId": "NA1",
            "timestamp": 1568348878867,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3148552462,
            "champion": 80,
            "platformId": "NA1",
            "timestamp": 1568346636339,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148534670,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1568345049184,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148508552,
            "champion": 201,
            "platformId": "NA1",
            "timestamp": 1568343798960,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148404625,
            "champion": 110,
            "platformId": "NA1",
            "timestamp": 1568336893418,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148389380,
            "champion": 1,
            "platformId": "NA1",
            "timestamp": 1568335781760,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3148347563,
            "champion": 91,
            "platformId": "NA1",
            "timestamp": 1568333084400,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3148350546,
            "champion": 68,
            "platformId": "NA1",
            "timestamp": 1568331367440,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148334771,
            "champion": 8,
            "platformId": "NA1",
            "timestamp": 1568329963780,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148299186,
            "champion": 110,
            "platformId": "NA1",
            "timestamp": 1568328377647,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3148294477,
            "champion": 126,
            "platformId": "NA1",
            "timestamp": 1568327061625,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3147652356,
            "champion": 31,
            "platformId": "NA1",
            "timestamp": 1568239837447,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3146984644,
            "champion": 80,
            "platformId": "NA1",
            "timestamp": 1568170532942,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3146976458,
            "champion": 15,
            "platformId": "NA1",
            "timestamp": 1568168943842,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3146349865,
            "champion": 1,
            "platformId": "NA1",
            "timestamp": 1568081868118,
            "queue": 450,
            "role": "DUO_CARRY",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3146331245,
            "champion": 21,
            "platformId": "NA1",
            "timestamp": 1568080109566,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3146294766,
            "champion": 74,
            "platformId": "NA1",
            "timestamp": 1568078723058,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3146267729,
            "champion": 61,
            "platformId": "NA1",
            "timestamp": 1568077214752,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3145812650,
            "champion": 117,
            "platformId": "NA1",
            "timestamp": 1568005338508,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3145727183,
            "champion": 74,
            "platformId": "NA1",
            "timestamp": 1568003659844,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3145741315,
            "champion": 202,
            "platformId": "NA1",
            "timestamp": 1568002358654,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3145651746,
            "champion": 223,
            "platformId": "NA1",
            "timestamp": 1568000041296,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3145556255,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1567998793084,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3145120894,
            "champion": 223,
            "platformId": "NA1",
            "timestamp": 1567966898993,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3145087837,
            "champion": 56,
            "platformId": "NA1",
            "timestamp": 1567965868307,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "BOTTOM",
            "gameId": 3144789436,
            "champion": 56,
            "platformId": "NA1",
            "timestamp": 1567917559028,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144782614,
            "champion": 268,
            "platformId": "NA1",
            "timestamp": 1567916159101,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144753494,
            "champion": 90,
            "platformId": "NA1",
            "timestamp": 1567914377982,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3144726008,
            "champion": 91,
            "platformId": "NA1",
            "timestamp": 1567912932096,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144729795,
            "champion": 25,
            "platformId": "NA1",
            "timestamp": 1567911766904,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3144622334,
            "champion": 50,
            "platformId": "NA1",
            "timestamp": 1567904024969,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3144595920,
            "champion": 117,
            "platformId": "NA1",
            "timestamp": 1567902517947,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "BOTTOM",
            "gameId": 3144557245,
            "champion": 112,
            "platformId": "NA1",
            "timestamp": 1567900275705,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144552074,
            "champion": 115,
            "platformId": "NA1",
            "timestamp": 1567898941185,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144333933,
            "champion": 115,
            "platformId": "NA1",
            "timestamp": 1567880646826,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144330413,
            "champion": 40,
            "platformId": "NA1",
            "timestamp": 1567879540895,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3144322008,
            "champion": 150,
            "platformId": "NA1",
            "timestamp": 1567877012257,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3143852254,
            "champion": 143,
            "platformId": "NA1",
            "timestamp": 1567819004521,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3143816278,
            "champion": 54,
            "platformId": "NA1",
            "timestamp": 1567817666179,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3140169487,
            "champion": 99,
            "platformId": "NA1",
            "timestamp": 1567405509505,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3138925429,
            "champion": 12,
            "platformId": "NA1",
            "timestamp": 1567303091973,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3138839077,
            "champion": 429,
            "platformId": "NA1",
            "timestamp": 1567301694834,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3138830477,
            "champion": 268,
            "platformId": "NA1",
            "timestamp": 1567299763633,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3138801638,
            "champion": 31,
            "platformId": "NA1",
            "timestamp": 1567297657478,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3138746566,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1567293899262,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3138709556,
            "champion": 54,
            "platformId": "NA1",
            "timestamp": 1567291987661,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3138694939,
            "champion": 80,
            "platformId": "NA1",
            "timestamp": 1567290657116,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3138313673,
            "champion": 37,
            "platformId": "NA1",
            "timestamp": 1567232736064,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3138299940,
            "champion": 78,
            "platformId": "NA1",
            "timestamp": 1567231410059,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3137511832,
            "champion": 101,
            "platformId": "NA1",
            "timestamp": 1567136748824,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3131956407,
            "champion": 50,
            "platformId": "NA1",
            "timestamp": 1566616647905,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3128742955,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1566274042323,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3125791257,
            "champion": 64,
            "platformId": "NA1",
            "timestamp": 1566000912355,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3123213511,
            "champion": 78,
            "platformId": "NA1",
            "timestamp": 1565761637333,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3123168339,
            "champion": 9,
            "platformId": "NA1",
            "timestamp": 1565760163839,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3123171315,
            "champion": 31,
            "platformId": "NA1",
            "timestamp": 1565758632702,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3123154503,
            "champion": 1,
            "platformId": "NA1",
            "timestamp": 1565757167207,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3123117612,
            "champion": 50,
            "platformId": "NA1",
            "timestamp": 1565755771638,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3123102600,
            "champion": 112,
            "platformId": "NA1",
            "timestamp": 1565754670665,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120624451,
            "champion": 64,
            "platformId": "NA1",
            "timestamp": 1565506276776,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120602124,
            "champion": 21,
            "platformId": "NA1",
            "timestamp": 1565505344879,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "JUNGLE",
            "gameId": 3120574152,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1565503266973,
            "queue": 450,
            "role": "NONE",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120557975,
            "champion": 64,
            "platformId": "NA1",
            "timestamp": 1565501928103,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3120538021,
            "champion": 25,
            "platformId": "NA1",
            "timestamp": 1565499873344,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3120509557,
            "champion": 101,
            "platformId": "NA1",
            "timestamp": 1565498157879,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120505193,
            "champion": 50,
            "platformId": "NA1",
            "timestamp": 1565497285764,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120249101,
            "champion": 50,
            "platformId": "NA1",
            "timestamp": 1565481013993,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120243818,
            "champion": 143,
            "platformId": "NA1",
            "timestamp": 1565479632921,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3120176142,
            "champion": 64,
            "platformId": "NA1",
            "timestamp": 1565472686997,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3119433263,
            "champion": 110,
            "platformId": "NA1",
            "timestamp": 1565411219481,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3119414166,
            "champion": 238,
            "platformId": "NA1",
            "timestamp": 1565409593842,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3119255569,
            "champion": 13,
            "platformId": "NA1",
            "timestamp": 1565400016422,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3119238195,
            "champion": 412,
            "platformId": "NA1",
            "timestamp": 1565398472607,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3114289234,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1564895996788,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3114268852,
            "champion": 13,
            "platformId": "NA1",
            "timestamp": 1564894085905,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3114260618,
            "champion": 25,
            "platformId": "NA1",
            "timestamp": 1564892511346,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3110661775,
            "champion": 9,
            "platformId": "NA1",
            "timestamp": 1564552538546,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3110634232,
            "champion": 555,
            "platformId": "NA1",
            "timestamp": 1564550668331,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3110616704,
            "champion": 111,
            "platformId": "NA1",
            "timestamp": 1564549015653,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3110589547,
            "champion": 31,
            "platformId": "NA1",
            "timestamp": 1564547523198,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "JUNGLE",
            "gameId": 3108803497,
            "champion": 1,
            "platformId": "NA1",
            "timestamp": 1564379115415,
            "queue": 450,
            "role": "NONE",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3108766535,
            "champion": 41,
            "platformId": "NA1",
            "timestamp": 1564377313128,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3108759992,
            "champion": 412,
            "platformId": "NA1",
            "timestamp": 1564375903850,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3108638201,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1564369784219,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3108617281,
            "champion": 53,
            "platformId": "NA1",
            "timestamp": 1564368069527,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3108584643,
            "champion": 111,
            "platformId": "NA1",
            "timestamp": 1564365907711,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3108543624,
            "champion": 90,
            "platformId": "NA1",
            "timestamp": 1564363945792,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3107915072,
            "champion": 17,
            "platformId": "NA1",
            "timestamp": 1564293665856,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3107893624,
            "champion": 24,
            "platformId": "NA1",
            "timestamp": 1564291226168,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3107722757,
            "champion": 15,
            "platformId": "NA1",
            "timestamp": 1564279741685,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3107693800,
            "champion": 432,
            "platformId": "NA1",
            "timestamp": 1564277894067,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3107668203,
            "champion": 57,
            "platformId": "NA1",
            "timestamp": 1564276705830,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3107639382,
            "champion": 12,
            "platformId": "NA1",
            "timestamp": 1564274762936,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3107615329,
            "champion": 41,
            "platformId": "NA1",
            "timestamp": 1564273515970,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3106602707,
            "champion": 91,
            "platformId": "NA1",
            "timestamp": 1564192770994,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "TOP",
            "gameId": 3106575322,
            "champion": 3,
            "platformId": "NA1",
            "timestamp": 1564191292420,
            "queue": 450,
            "role": "SOLO",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3106537936,
            "champion": 112,
            "platformId": "NA1",
            "timestamp": 1564189429148,
            "queue": 450,
            "role": "DUO",
            "season": 13
        },
        {
            "lane": "MID",
            "gameId": 3104979716,
            "champion": 80,
            "platformId": "NA1",
            "timestamp": 1564020754548,
            "queue": 450,
            "role": "DUO_SUPPORT",
            "season": 13
        },
        {
            "lane": "NONE",
            "gameId": 3104969929,
            "champion": 104,
            "platformId": "NA1",
            "timestamp": 1564019118811,
            "queue": 450,
            "role": "DUO",
            "season": 13
        }
    ],
    "endIndex": 100,
    "startIndex": 0,
    "totalGames": 139
};